<?php
/**
 * @file
 * Code for the The Sorrow And The Pride (TSATP) feature.
 */

include_once 'the_sorrow_and_the_pride.features.inc';


/**
 * Implements hook_menu().
 */
function the_sorrow_and_the_pride_menu() {
  $items = array();

  $items['home'] = array(
    'title' => 'The Sorrow And The Pride',
    'page callback' => 'the_sorrow_and_the_pride_home',
    'access callback' => TRUE,
  );

  return $items;
}

function the_sorrow_and_the_pride_home() {
  return '<p>The names on NZ Memorials.</p>';

}

/**
 * Implements hook_block_info().
 */
function the_sorrow_and_the_pride_block_info() {
  // This example comes from node.module.
  $blocks['tsatp_footer'] = array(
    'info' => t('TSATP footer (the_sorrow_and_the_pride.module)'),
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function the_sorrow_and_the_pride_block_view($delta = '') {
  switch ($delta) {
    case 'tsatp_footer':
      $block['subject'] = '';
      $block['content'] = '<p>A project by team <a href="http://2016.hackerspace.govhack.org/content/tabula-rasa-tsatp">Tabula Rasa</a> for GovHackNZ 2016.</p>';
      return $block;
  }
}
